### ISSUE TITLE
commits is an object

### ISSUE THREAD

**Issue by diananova** [sladyn98/hawk-eye-npm#1]
hey so I noticed that the information we really need (status checks) is inside commits, which on the command line is printed as an object. Is it supposed to be this way? Or should we break it down so that the user can see all the information (print the children of object commits?
![image](https://user-images.githubusercontent.com/24480679/107975176-fda3c980-6fb7-11eb-85c0-35dfa7cbf2ce.png)

**Comment by sladyn98** [comment]
@diananova Yeah this was the issue I faced too, I was thinking maybe the CLI can parse the data. But if you can figure out a way to return just a json object with the status name, the url and the status. That would be amazing

**Comment by sladyn98** [comment]
You can open a PR to this repo itself

**Comment by diananova** [comment]
ok great I'll try and work on that!

**Comment by diananova** [comment]
closed by #2
